import { loadSettings } from './settings.mjs';
// Keep the sidebar ID stable for navbar links; an explicit empty array disables generated items.
export default { docs: loadSettings().sidebar ?? [{ type: 'autogenerated', dirName: '.' }] };
