name: Lint CSS

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-css:
    uses: rtCamp/wp-shared-workflows/.github/workflows/ci-lint-css.yml@v1
    with:
      working-dir: plugins/acme-blocks
      node-version: "22"
      lint-command: npm run lint:css
