name: Test accessibility

on:
  pull_request:
    types:
      - labeled
      - synchronize

permissions:
  contents: read

jobs:
  test-a11y:
    if: contains(github.event.pull_request.labels.*.name, 'Run a11y')
    uses: rtCamp/wp-shared-workflows/.github/workflows/ci-test-a11y.yml@v1
    with:
      working-dir: themes/acme-theme
      node-version: "22"
      build-command: npm run build:prod
      test-command: npm run test:a11y
