name: Version monitor

on:
  schedule:
    - cron: "0 3 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  version-monitor:
    permissions:
      contents: write
      pull-requests: write
    uses: rtCamp/wp-shared-workflows/.github/workflows/version-monitor.yml@v1
    with:
      base-branch: main
      pr-label: version-monitor
      pr-assignees: acme-maintainer
